# Generated by Django 4.1 on 2022-08-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guildmanager_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='faction',
            field=models.TextField(choices=[('ALLIANCE', 'Alliance'), ('HORDE', 'Horde')], default='Alliance'),
        ),
        migrations.AddField(
            model_name='char',
            name='game',
            field=models.ManyToManyField(to='guildmanager_api.game'),
        ),
        migrations.AddField(
            model_name='char',
            name='guild',
            field=models.ManyToManyField(to='guildmanager_api.guild'),
        ),
        migrations.AddField(
            model_name='char',
            name='role',
            field=models.TextField(choices=[('DRUID', 'Druid'), ('HUNTER', 'Hunter'), ('MAGE', 'Mage'), ('PALADIN', 'Paladin'), ('PRIEST', 'Priest'), ('ROGUE', 'Rogue'), ('SHAMAN', 'Shaman'), ('WARLOCK', 'Warlock'), ('WARRIOR', 'Warrior')], default='Druid'),
        ),
        migrations.AddField(
            model_name='char',
            name='server',
            field=models.TextField(choices=[('AMNENNAR', 'Amnennar(French)'), ('ASHBRINGER', 'Ashbringer(English)')], default='Ashbringer'),
        ),
        migrations.AddField(
            model_name='char',
            name='spec',
            field=models.TextField(choices=[('DPS', 'DPS'), ('TANK', 'Tank'), ('HEALER', 'Healer'), ('HYBRID', 'Hybrid')], default='DPS'),
        ),
        migrations.AddField(
            model_name='guild',
            name='description_full',
            field=models.TextField(default='Guild description'),
        ),
        migrations.AddField(
            model_name='guild',
            name='description_short',
            field=models.TextField(default='New Guild'),
        ),
        migrations.AddField(
            model_name='guild',
            name='faction',
            field=models.TextField(choices=[('ALLIANCE', 'Alliance'), ('HORDE', 'Horde')], default='Alliance'),
        ),
        migrations.AddField(
            model_name='guild',
            name='game',
            field=models.ManyToManyField(to='guildmanager_api.game'),
        ),
        migrations.AddField(
            model_name='guild',
            name='server',
            field=models.TextField(choices=[('AMNENNAR', 'Amnennar(French)'), ('ASHBRINGER', 'Ashbringer(English)')], default='Ashbringer'),
        ),
    ]
