# Generated by Django 4.1 on 2022-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guildmanager_api', '0002_char_faction_char_game_char_guild_char_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='game',
            field=models.ManyToManyField(default=[2], to='guildmanager_api.game'),
        ),
    ]
