# Generated by Django 4.1 on 2022-08-16 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guildmanager_api', '0005_guild_guild_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
